figure(1)
plot(output.result.solution.phase.time,output.result.solution.phase.control(:,1), 'k','LineWidth',1.5)
xlabel('t/s',  'FontSize',15)
ylabel('P/N' ,'FontSize',15)
title('推力','FontSize',20)
figure(2)
plot(output.result.solution.phase.time,output.result.solution.phase.state(:,1), 'k','LineWidth',1.5)
xlabel('t/s',  'FontSize',15)
ylabel('V/m/s' ,'FontSize',15)
title('速度','FontSize',20)
figure(3)
plot(output.result.solution.phase.time,output.result.solution.phase.state(:,2)*180/pi, 'k','LineWidth',1.5)
xlabel('t/s',  'FontSize',15)
ylabel('\theta/(°)' ,'FontSize',15)
title('弹道倾角','FontSize',20)
figure(4)
plot(output.result.solution.phase.state(:,3),output.result.solution.phase.state(:,4), 'k','LineWidth',1.5)
xlabel('x/m',  'FontSize',15)
ylabel('y/m' ,'FontSize',15)
title('飞行轨迹','FontSize',20)
figure(5)
plot(output.result.solution.phase.time,output.result.solution.phase.control(:,2)*180/pi, 'k','LineWidth',1.5)
xlabel('t/s',  'FontSize',15)
ylabel('\alpha/(°)' ,'FontSize',15)
title('攻角','FontSize',20)